sudo: required
services:
  - docker

before_install:
  - docker build -t olu180/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run olu180/react-test npm test -- --coverage

after_success:
  - docker build -t olu180/multi-client ./client
  - docker build -t olu180/multi-nginx ./nginx
  - docker build -t olu180/multi-server ./server
  - docker build -t olu180/multi-worker ./worker
  # log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push olu180/multi-client
  - docker push olu180/multi-nginx
  - docker push olu180/multi-server
  - docker push olu180/multi-worker